package org.dreamlab.Classes;

public enum Deployment {
    EDGE, WORK_STEAL_FROM_CLOUD, CLOUD, RESCHEDULED_CLOUD, RESCHEDULED_DROP_TIME, DROP_TIME, RESCHEDULED_DROP_COST, DROP_COST, EXPIRED_EDGE, EXPIRED_CLOUD, MISSED_EDGE, MISSED_CLOUD, GATEKEEPER_RESCHEDULED, GATEKEEPER_RESCHEDULED_DROP_TIME
}
