package org.dreamlab.Classes;

public enum DNNModels {
    HAZARD_VEST, DISTANCE_ESTIMATION_OBJECT, DISTANCE_ESTIMATION_VIP, CROWD_DENSITY, MASK_DETECTION, BODY_POSE_ESTIMATION, HAND_POSE_ESTIMATION, DISTANCE_ESTIMATION;
}
