// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userapplicationdata.proto

package org.dreamlab.ApplicationDetails.GrpcGeneratedFiles;

public interface AckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.Ack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
