// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userapplicationdata.proto

package org.dreamlab.ApplicationDetails.GrpcGeneratedFiles;

public final class Userapplicationdata {
  private Userapplicationdata() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_dreamlab_ApplicationDetails_GrpcGeneratedFiles_Ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_dreamlab_ApplicationDetails_GrpcGeneratedFiles_Ack_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_dreamlab_ApplicationDetails_GrpcGeneratedFiles_UserApplicationInput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_dreamlab_ApplicationDetails_GrpcGeneratedFiles_UserApplicationInput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031userapplicationdata.proto\0222org.dreamla" +
      "b.ApplicationDetails.GrpcGeneratedFiles\"" +
      "\026\n\003Ack\022\017\n\007message\030\001 \001(\t\"\354\001\n\024UserApplicat" +
      "ionInput\022\016\n\006UserId\030\001 \001(\t\022c\n\010userMode\030\002 \003" +
      "(\0162Q.org.dreamlab.ApplicationDetails.Grp" +
      "cGeneratedFiles.UserApplicationInput.Use" +
      "rMode\022\020\n\010drone_id\030\003 \001(\t\"M\n\010UserMode\022\013\n\007W" +
      "ALKING\020\000\022\013\n\007RUNNING\020\001\022\022\n\016COVID_ADVISORY\020" +
      "\002\022\023\n\017POSE_ESTIMATION\020\0032\247\001\n\017UserApplicati" +
      "on\022\223\001\n\014addUserInput\022H.org.dreamlab.Appli" +
      "cationDetails.GrpcGeneratedFiles.UserApp" +
      "licationInput\0327.org.dreamlab.Application" +
      "Details.GrpcGeneratedFiles.Ack\"\000B\002P\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_dreamlab_ApplicationDetails_GrpcGeneratedFiles_Ack_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_dreamlab_ApplicationDetails_GrpcGeneratedFiles_Ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_dreamlab_ApplicationDetails_GrpcGeneratedFiles_Ack_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_org_dreamlab_ApplicationDetails_GrpcGeneratedFiles_UserApplicationInput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_dreamlab_ApplicationDetails_GrpcGeneratedFiles_UserApplicationInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_dreamlab_ApplicationDetails_GrpcGeneratedFiles_UserApplicationInput_descriptor,
        new java.lang.String[] { "UserId", "UserMode", "DroneId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
