// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userapplicationdata.proto

package org.dreamlab.ApplicationDetails.GrpcGeneratedFiles;

/**
 * Protobuf type {@code org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput}
 */
public final class UserApplicationInput extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput)
    UserApplicationInputOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserApplicationInput.newBuilder() to construct.
  private UserApplicationInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserApplicationInput() {
    userId_ = "";
    userMode_ = java.util.Collections.emptyList();
    droneId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserApplicationInput();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserApplicationInput(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            userId_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              userMode_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            userMode_.add(rawValue);
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int oldLimit = input.pushLimit(length);
            while(input.getBytesUntilLimit() > 0) {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                userMode_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              userMode_.add(rawValue);
            }
            input.popLimit(oldLimit);
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            droneId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        userMode_ = java.util.Collections.unmodifiableList(userMode_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.Userapplicationdata.internal_static_org_dreamlab_ApplicationDetails_GrpcGeneratedFiles_UserApplicationInput_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.Userapplicationdata.internal_static_org_dreamlab_ApplicationDetails_GrpcGeneratedFiles_UserApplicationInput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.class, org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.Builder.class);
  }

  /**
   * Protobuf enum {@code org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode}
   */
  public enum UserMode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>WALKING = 0;</code>
     */
    WALKING(0),
    /**
     * <code>RUNNING = 1;</code>
     */
    RUNNING(1),
    /**
     * <code>COVID_ADVISORY = 2;</code>
     */
    COVID_ADVISORY(2),
    /**
     * <code>POSE_ESTIMATION = 3;</code>
     */
    POSE_ESTIMATION(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>WALKING = 0;</code>
     */
    public static final int WALKING_VALUE = 0;
    /**
     * <code>RUNNING = 1;</code>
     */
    public static final int RUNNING_VALUE = 1;
    /**
     * <code>COVID_ADVISORY = 2;</code>
     */
    public static final int COVID_ADVISORY_VALUE = 2;
    /**
     * <code>POSE_ESTIMATION = 3;</code>
     */
    public static final int POSE_ESTIMATION_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UserMode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static UserMode forNumber(int value) {
      switch (value) {
        case 0: return WALKING;
        case 1: return RUNNING;
        case 2: return COVID_ADVISORY;
        case 3: return POSE_ESTIMATION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserMode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserMode>() {
            public UserMode findValueByNumber(int number) {
              return UserMode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.getDescriptor().getEnumTypes().get(0);
    }

    private static final UserMode[] VALUES = values();

    public static UserMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UserMode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode)
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private volatile java.lang.Object userId_;
  /**
   * <code>string UserId = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <code>string UserId = 1;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERMODE_FIELD_NUMBER = 2;
  private java.util.List<java.lang.Integer> userMode_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode> userMode_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode>() {
            public org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode convert(java.lang.Integer from) {
              @SuppressWarnings("deprecation")
              org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode result = org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode.valueOf(from);
              return result == null ? org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
   * @return A list containing the userMode.
   */
  @java.lang.Override
  public java.util.List<org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode> getUserModeList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode>(userMode_, userMode_converter_);
  }
  /**
   * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
   * @return The count of userMode.
   */
  @java.lang.Override
  public int getUserModeCount() {
    return userMode_.size();
  }
  /**
   * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
   * @param index The index of the element to return.
   * @return The userMode at the given index.
   */
  @java.lang.Override
  public org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode getUserMode(int index) {
    return userMode_converter_.convert(userMode_.get(index));
  }
  /**
   * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
   * @return A list containing the enum numeric values on the wire for userMode.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getUserModeValueList() {
    return userMode_;
  }
  /**
   * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of userMode at the given index.
   */
  @java.lang.Override
  public int getUserModeValue(int index) {
    return userMode_.get(index);
  }
  private int userModeMemoizedSerializedSize;

  public static final int DRONE_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object droneId_;
  /**
   * <code>string drone_id = 3;</code>
   * @return The droneId.
   */
  @java.lang.Override
  public java.lang.String getDroneId() {
    java.lang.Object ref = droneId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      droneId_ = s;
      return s;
    }
  }
  /**
   * <code>string drone_id = 3;</code>
   * @return The bytes for droneId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDroneIdBytes() {
    java.lang.Object ref = droneId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      droneId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
    }
    if (getUserModeList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(userModeMemoizedSerializedSize);
    }
    for (int i = 0; i < userMode_.size(); i++) {
      output.writeEnumNoTag(userMode_.get(i));
    }
    if (!getDroneIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, droneId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < userMode_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(userMode_.get(i));
      }
      size += dataSize;
      if (!getUserModeList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }userModeMemoizedSerializedSize = dataSize;
    }
    if (!getDroneIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, droneId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput)) {
      return super.equals(obj);
    }
    org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput other = (org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput) obj;

    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (!userMode_.equals(other.userMode_)) return false;
    if (!getDroneId()
        .equals(other.getDroneId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    if (getUserModeCount() > 0) {
      hash = (37 * hash) + USERMODE_FIELD_NUMBER;
      hash = (53 * hash) + userMode_.hashCode();
    }
    hash = (37 * hash) + DRONE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDroneId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput)
      org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.Userapplicationdata.internal_static_org_dreamlab_ApplicationDetails_GrpcGeneratedFiles_UserApplicationInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.Userapplicationdata.internal_static_org_dreamlab_ApplicationDetails_GrpcGeneratedFiles_UserApplicationInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.class, org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.Builder.class);
    }

    // Construct using org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userId_ = "";

      userMode_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      droneId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.Userapplicationdata.internal_static_org_dreamlab_ApplicationDetails_GrpcGeneratedFiles_UserApplicationInput_descriptor;
    }

    @java.lang.Override
    public org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput getDefaultInstanceForType() {
      return org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.getDefaultInstance();
    }

    @java.lang.Override
    public org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput build() {
      org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput buildPartial() {
      org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput result = new org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput(this);
      int from_bitField0_ = bitField0_;
      result.userId_ = userId_;
      if (((bitField0_ & 0x00000001) != 0)) {
        userMode_ = java.util.Collections.unmodifiableList(userMode_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.userMode_ = userMode_;
      result.droneId_ = droneId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput) {
        return mergeFrom((org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput other) {
      if (other == org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.getDefaultInstance()) return this;
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (!other.userMode_.isEmpty()) {
        if (userMode_.isEmpty()) {
          userMode_ = other.userMode_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureUserModeIsMutable();
          userMode_.addAll(other.userMode_);
        }
        onChanged();
      }
      if (!other.getDroneId().isEmpty()) {
        droneId_ = other.droneId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object userId_ = "";
    /**
     * <code>string UserId = 1;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string UserId = 1;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string UserId = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string UserId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>string UserId = 1;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> userMode_ =
      java.util.Collections.emptyList();
    private void ensureUserModeIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        userMode_ = new java.util.ArrayList<java.lang.Integer>(userMode_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
     * @return A list containing the userMode.
     */
    public java.util.List<org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode> getUserModeList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode>(userMode_, userMode_converter_);
    }
    /**
     * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
     * @return The count of userMode.
     */
    public int getUserModeCount() {
      return userMode_.size();
    }
    /**
     * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
     * @param index The index of the element to return.
     * @return The userMode at the given index.
     */
    public org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode getUserMode(int index) {
      return userMode_converter_.convert(userMode_.get(index));
    }
    /**
     * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
     * @param index The index to set the value at.
     * @param value The userMode to set.
     * @return This builder for chaining.
     */
    public Builder setUserMode(
        int index, org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureUserModeIsMutable();
      userMode_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
     * @param value The userMode to add.
     * @return This builder for chaining.
     */
    public Builder addUserMode(org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureUserModeIsMutable();
      userMode_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
     * @param values The userMode to add.
     * @return This builder for chaining.
     */
    public Builder addAllUserMode(
        java.lang.Iterable<? extends org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode> values) {
      ensureUserModeIsMutable();
      for (org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode value : values) {
        userMode_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserMode() {
      userMode_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
     * @return A list containing the enum numeric values on the wire for userMode.
     */
    public java.util.List<java.lang.Integer>
    getUserModeValueList() {
      return java.util.Collections.unmodifiableList(userMode_);
    }
    /**
     * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of userMode at the given index.
     */
    public int getUserModeValue(int index) {
      return userMode_.get(index);
    }
    /**
     * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of userMode at the given index.
     * @return This builder for chaining.
     */
    public Builder setUserModeValue(
        int index, int value) {
      ensureUserModeIsMutable();
      userMode_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
     * @param value The enum numeric value on the wire for userMode to add.
     * @return This builder for chaining.
     */
    public Builder addUserModeValue(int value) {
      ensureUserModeIsMutable();
      userMode_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
     * @param values The enum numeric values on the wire for userMode to add.
     * @return This builder for chaining.
     */
    public Builder addAllUserModeValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureUserModeIsMutable();
      for (int value : values) {
        userMode_.add(value);
      }
      onChanged();
      return this;
    }

    private java.lang.Object droneId_ = "";
    /**
     * <code>string drone_id = 3;</code>
     * @return The droneId.
     */
    public java.lang.String getDroneId() {
      java.lang.Object ref = droneId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        droneId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string drone_id = 3;</code>
     * @return The bytes for droneId.
     */
    public com.google.protobuf.ByteString
        getDroneIdBytes() {
      java.lang.Object ref = droneId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        droneId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string drone_id = 3;</code>
     * @param value The droneId to set.
     * @return This builder for chaining.
     */
    public Builder setDroneId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      droneId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string drone_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDroneId() {
      
      droneId_ = getDefaultInstance().getDroneId();
      onChanged();
      return this;
    }
    /**
     * <code>string drone_id = 3;</code>
     * @param value The bytes for droneId to set.
     * @return This builder for chaining.
     */
    public Builder setDroneIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      droneId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput)
  }

  // @@protoc_insertion_point(class_scope:org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput)
  private static final org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput();
  }

  public static org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserApplicationInput>
      PARSER = new com.google.protobuf.AbstractParser<UserApplicationInput>() {
    @java.lang.Override
    public UserApplicationInput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserApplicationInput(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserApplicationInput> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserApplicationInput> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

