// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userapplicationdata.proto

package org.dreamlab.ApplicationDetails.GrpcGeneratedFiles;

public interface UserApplicationInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string UserId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string UserId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
   * @return A list containing the userMode.
   */
  java.util.List<org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode> getUserModeList();
  /**
   * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
   * @return The count of userMode.
   */
  int getUserModeCount();
  /**
   * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
   * @param index The index of the element to return.
   * @return The userMode at the given index.
   */
  org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode getUserMode(int index);
  /**
   * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
   * @return A list containing the enum numeric values on the wire for userMode.
   */
  java.util.List<java.lang.Integer>
  getUserModeValueList();
  /**
   * <code>repeated .org.dreamlab.ApplicationDetails.GrpcGeneratedFiles.UserApplicationInput.UserMode userMode = 2;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of userMode at the given index.
   */
  int getUserModeValue(int index);

  /**
   * <code>string drone_id = 3;</code>
   * @return The droneId.
   */
  java.lang.String getDroneId();
  /**
   * <code>string drone_id = 3;</code>
   * @return The bytes for droneId.
   */
  com.google.protobuf.ByteString
      getDroneIdBytes();
}
