FROM ubuntu:focal

LABEL "author"="sumanraj@iisc.ac.in" "team"="Dream Lab"

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt update \
    && apt -y upgrade \
    && apt install -y \
        build-essential \
        ffmpeg \
        # gcc-10-base \
        git \
        ifstat \
        iperf3 \
        iproute2 \
        iputils-ping \
        # libapt-pkg6.0 \
        # libcrypt1 \
        # libffi7 \
        # libgcc-s1 \
        # libhogweed5 \
        # libncurses6 \
        # libncursesw6 \
        # libnettle7 \
        libpam-modules \
        libpcre2-8-0 \
        # libprocps8 \
        libsm6 \
        # libtinfo6 \
        libxext6 \
        # logsave \
        net-tools \
        openjdk-11-jdk \
        python3-pip \
        python3 \
        vim \
    && pip3 install \
        'absl-py==1.0.0' \
        'cachetools==4.2.4' \
        'certifi==2021.10.8' \
        'charset-normalizer==2.0.9' \
        'cycler==0.11.0' \
        'Cython==0.29.25' \
        'fonttools==4.28.3' \
        'google-auth==2.3.3' \
        'google-auth-oauthlib==0.4.6' \
        'grpcio==1.42.0' \
        'grpcio-tools==1.42.0' \
        'idna==3.3' \
        'importlib-metadata==4.8.2' \
        'joblib==1.1.0' \
        'kiwisolver==1.3.2' \
        'Markdown==3.3.6' \
        'matplotlib==3.5.0' \
        'numpy==1.21.4' \
        'oauthlib==3.1.1' \
        'opencv-python==4.9.0.80' \
        'packaging==21.3' \
        'pandas==1.3.4' \
        'Pillow==8.4.0' \
        'protobuf==3.19.1' \
        'psutil==5.9.8' \
        'py-cpuinfo==9.0.0' \
        'pyasn1==0.4.8' \
        'pyasn1-modules==0.2.8' \
        'pycocotools==2.0.3' \
        'pyparsing==3.0.6' \
        'python-dateutil==2.8.2' \
        'pytz==2021.3' \
        'PyYAML==6.0' \
        'requests==2.26.0' \
        'requests-oauthlib==1.3.0' \
        'rsa==4.8' \
        'scikit-learn==1.0.1' \
        'scipy==1.7.3' \
        'seaborn==0.11.2' \
        'setuptools-scm==6.3.2' \
        'six==1.16.0' \
        'sklearn==0.0' \
        'tensorboard==2.7.0' \
        'tensorboard-data-server==0.6.1' \
        'tensorboard-plugin-wit==1.8.0' \
        'thop==0.1.1.post2209072238' \
        'threadpoolctl==3.0.0' \
        'tomli==1.2.2' \
        'torch==1.10.0' \
        'torchvision==0.11.1' \
        'tqdm==4.66.2' \
        'traitlets==5.1.1' \
        'typing-extensions==4.0.1' \
        'ultralytics==8.1.37' \
        'urllib3==1.26.7' \
        'Werkzeug==2.0.2' \
        'zipp==3.6.0' \
    && pip3 install git+https://github.com/NVIDIA-AI-IOT/trt_pose.git@v0.0.1

COPY . /home/ultraviolet

RUN /bin/bash
