// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata

package org.dreamlab.gRPCHandler;

public interface AckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.dreamlab.gRPCHandler.Ack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string task_id = 2;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <code>string task_id = 2;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <code>string batch_id = 3;</code>
   * @return The batchId.
   */
  java.lang.String getBatchId();
  /**
   * <code>string batch_id = 3;</code>
   * @return The bytes for batchId.
   */
  com.google.protobuf.ByteString
      getBatchIdBytes();

  /**
   * <code>string result = 4;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 4;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
