// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata.proto

package org.dreamlab.gRPCHandler;

/**
 * Protobuf type {@code org.dreamlab.gRPCHandler.BatchMetadata}
 */
public  final class BatchMetadata extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.dreamlab.gRPCHandler.BatchMetadata)
    BatchMetadataOrBuilder {
  // Use BatchMetadata.newBuilder() to construct.
  private BatchMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BatchMetadata() {
    droneId_ = "";
    batchId_ = "";
    startTime_ = 0L;
    endTime_ = 0L;
    batchSize_ = 0;
    batchDuration_ = 0;
    filePath_ = "";
    isDummyData_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private BatchMetadata(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            droneId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            batchId_ = s;
            break;
          }
          case 24: {

            startTime_ = input.readInt64();
            break;
          }
          case 32: {

            endTime_ = input.readInt64();
            break;
          }
          case 40: {

            batchSize_ = input.readInt32();
            break;
          }
          case 48: {

            batchDuration_ = input.readInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            filePath_ = s;
            break;
          }
          case 64: {

            isDummyData_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.dreamlab.gRPCHandler.Metadata.internal_static_org_dreamlab_gRPCHandler_BatchMetadata_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.dreamlab.gRPCHandler.Metadata.internal_static_org_dreamlab_gRPCHandler_BatchMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.dreamlab.gRPCHandler.BatchMetadata.class, org.dreamlab.gRPCHandler.BatchMetadata.Builder.class);
  }

  public static final int DRONE_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object droneId_;
  /**
   * <code>optional string drone_id = 1;</code>
   */
  public java.lang.String getDroneId() {
    java.lang.Object ref = droneId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      droneId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string drone_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDroneIdBytes() {
    java.lang.Object ref = droneId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      droneId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BATCH_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object batchId_;
  /**
   * <code>optional string batch_id = 2;</code>
   */
  public java.lang.String getBatchId() {
    java.lang.Object ref = batchId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      batchId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string batch_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBatchIdBytes() {
    java.lang.Object ref = batchId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      batchId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int START_TIME_FIELD_NUMBER = 3;
  private long startTime_;
  /**
   * <code>optional int64 start_time = 3;</code>
   */
  public long getStartTime() {
    return startTime_;
  }

  public static final int END_TIME_FIELD_NUMBER = 4;
  private long endTime_;
  /**
   * <code>optional int64 end_time = 4;</code>
   */
  public long getEndTime() {
    return endTime_;
  }

  public static final int BATCH_SIZE_FIELD_NUMBER = 5;
  private int batchSize_;
  /**
   * <code>optional int32 batch_size = 5;</code>
   */
  public int getBatchSize() {
    return batchSize_;
  }

  public static final int BATCH_DURATION_FIELD_NUMBER = 6;
  private int batchDuration_;
  /**
   * <code>optional int32 batch_duration = 6;</code>
   */
  public int getBatchDuration() {
    return batchDuration_;
  }

  public static final int FILE_PATH_FIELD_NUMBER = 7;
  private volatile java.lang.Object filePath_;
  /**
   * <code>optional string file_path = 7;</code>
   */
  public java.lang.String getFilePath() {
    java.lang.Object ref = filePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filePath_ = s;
      return s;
    }
  }
  /**
   * <code>optional string file_path = 7;</code>
   */
  public com.google.protobuf.ByteString
      getFilePathBytes() {
    java.lang.Object ref = filePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_DUMMY_DATA_FIELD_NUMBER = 8;
  private boolean isDummyData_;
  /**
   * <code>optional bool is_dummy_data = 8;</code>
   */
  public boolean getIsDummyData() {
    return isDummyData_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDroneIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, droneId_);
    }
    if (!getBatchIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, batchId_);
    }
    if (startTime_ != 0L) {
      output.writeInt64(3, startTime_);
    }
    if (endTime_ != 0L) {
      output.writeInt64(4, endTime_);
    }
    if (batchSize_ != 0) {
      output.writeInt32(5, batchSize_);
    }
    if (batchDuration_ != 0) {
      output.writeInt32(6, batchDuration_);
    }
    if (!getFilePathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, filePath_);
    }
    if (isDummyData_ != false) {
      output.writeBool(8, isDummyData_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDroneIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, droneId_);
    }
    if (!getBatchIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, batchId_);
    }
    if (startTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, startTime_);
    }
    if (endTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, endTime_);
    }
    if (batchSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, batchSize_);
    }
    if (batchDuration_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, batchDuration_);
    }
    if (!getFilePathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, filePath_);
    }
    if (isDummyData_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, isDummyData_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.dreamlab.gRPCHandler.BatchMetadata)) {
      return super.equals(obj);
    }
    org.dreamlab.gRPCHandler.BatchMetadata other = (org.dreamlab.gRPCHandler.BatchMetadata) obj;

    boolean result = true;
    result = result && getDroneId()
        .equals(other.getDroneId());
    result = result && getBatchId()
        .equals(other.getBatchId());
    result = result && (getStartTime()
        == other.getStartTime());
    result = result && (getEndTime()
        == other.getEndTime());
    result = result && (getBatchSize()
        == other.getBatchSize());
    result = result && (getBatchDuration()
        == other.getBatchDuration());
    result = result && getFilePath()
        .equals(other.getFilePath());
    result = result && (getIsDummyData()
        == other.getIsDummyData());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + DRONE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDroneId().hashCode();
    hash = (37 * hash) + BATCH_ID_FIELD_NUMBER;
    hash = (53 * hash) + getBatchId().hashCode();
    hash = (37 * hash) + START_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartTime());
    hash = (37 * hash) + END_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndTime());
    hash = (37 * hash) + BATCH_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getBatchSize();
    hash = (37 * hash) + BATCH_DURATION_FIELD_NUMBER;
    hash = (53 * hash) + getBatchDuration();
    hash = (37 * hash) + FILE_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getFilePath().hashCode();
    hash = (37 * hash) + IS_DUMMY_DATA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsDummyData());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.dreamlab.gRPCHandler.BatchMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.dreamlab.gRPCHandler.BatchMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.dreamlab.gRPCHandler.BatchMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.dreamlab.gRPCHandler.BatchMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.dreamlab.gRPCHandler.BatchMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.dreamlab.gRPCHandler.BatchMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.dreamlab.gRPCHandler.BatchMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.dreamlab.gRPCHandler.BatchMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.dreamlab.gRPCHandler.BatchMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.dreamlab.gRPCHandler.BatchMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.dreamlab.gRPCHandler.BatchMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.dreamlab.gRPCHandler.BatchMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.dreamlab.gRPCHandler.BatchMetadata)
      org.dreamlab.gRPCHandler.BatchMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.dreamlab.gRPCHandler.Metadata.internal_static_org_dreamlab_gRPCHandler_BatchMetadata_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.dreamlab.gRPCHandler.Metadata.internal_static_org_dreamlab_gRPCHandler_BatchMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.dreamlab.gRPCHandler.BatchMetadata.class, org.dreamlab.gRPCHandler.BatchMetadata.Builder.class);
    }

    // Construct using org.dreamlab.gRPCHandler.BatchMetadata.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      droneId_ = "";

      batchId_ = "";

      startTime_ = 0L;

      endTime_ = 0L;

      batchSize_ = 0;

      batchDuration_ = 0;

      filePath_ = "";

      isDummyData_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.dreamlab.gRPCHandler.Metadata.internal_static_org_dreamlab_gRPCHandler_BatchMetadata_descriptor;
    }

    public org.dreamlab.gRPCHandler.BatchMetadata getDefaultInstanceForType() {
      return org.dreamlab.gRPCHandler.BatchMetadata.getDefaultInstance();
    }

    public org.dreamlab.gRPCHandler.BatchMetadata build() {
      org.dreamlab.gRPCHandler.BatchMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.dreamlab.gRPCHandler.BatchMetadata buildPartial() {
      org.dreamlab.gRPCHandler.BatchMetadata result = new org.dreamlab.gRPCHandler.BatchMetadata(this);
      result.droneId_ = droneId_;
      result.batchId_ = batchId_;
      result.startTime_ = startTime_;
      result.endTime_ = endTime_;
      result.batchSize_ = batchSize_;
      result.batchDuration_ = batchDuration_;
      result.filePath_ = filePath_;
      result.isDummyData_ = isDummyData_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.dreamlab.gRPCHandler.BatchMetadata) {
        return mergeFrom((org.dreamlab.gRPCHandler.BatchMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.dreamlab.gRPCHandler.BatchMetadata other) {
      if (other == org.dreamlab.gRPCHandler.BatchMetadata.getDefaultInstance()) return this;
      if (!other.getDroneId().isEmpty()) {
        droneId_ = other.droneId_;
        onChanged();
      }
      if (!other.getBatchId().isEmpty()) {
        batchId_ = other.batchId_;
        onChanged();
      }
      if (other.getStartTime() != 0L) {
        setStartTime(other.getStartTime());
      }
      if (other.getEndTime() != 0L) {
        setEndTime(other.getEndTime());
      }
      if (other.getBatchSize() != 0) {
        setBatchSize(other.getBatchSize());
      }
      if (other.getBatchDuration() != 0) {
        setBatchDuration(other.getBatchDuration());
      }
      if (!other.getFilePath().isEmpty()) {
        filePath_ = other.filePath_;
        onChanged();
      }
      if (other.getIsDummyData() != false) {
        setIsDummyData(other.getIsDummyData());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.dreamlab.gRPCHandler.BatchMetadata parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.dreamlab.gRPCHandler.BatchMetadata) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object droneId_ = "";
    /**
     * <code>optional string drone_id = 1;</code>
     */
    public java.lang.String getDroneId() {
      java.lang.Object ref = droneId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        droneId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string drone_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDroneIdBytes() {
      java.lang.Object ref = droneId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        droneId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string drone_id = 1;</code>
     */
    public Builder setDroneId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      droneId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string drone_id = 1;</code>
     */
    public Builder clearDroneId() {
      
      droneId_ = getDefaultInstance().getDroneId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string drone_id = 1;</code>
     */
    public Builder setDroneIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      droneId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object batchId_ = "";
    /**
     * <code>optional string batch_id = 2;</code>
     */
    public java.lang.String getBatchId() {
      java.lang.Object ref = batchId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        batchId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string batch_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBatchIdBytes() {
      java.lang.Object ref = batchId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        batchId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string batch_id = 2;</code>
     */
    public Builder setBatchId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      batchId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string batch_id = 2;</code>
     */
    public Builder clearBatchId() {
      
      batchId_ = getDefaultInstance().getBatchId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string batch_id = 2;</code>
     */
    public Builder setBatchIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      batchId_ = value;
      onChanged();
      return this;
    }

    private long startTime_ ;
    /**
     * <code>optional int64 start_time = 3;</code>
     */
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <code>optional int64 start_time = 3;</code>
     */
    public Builder setStartTime(long value) {
      
      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 start_time = 3;</code>
     */
    public Builder clearStartTime() {
      
      startTime_ = 0L;
      onChanged();
      return this;
    }

    private long endTime_ ;
    /**
     * <code>optional int64 end_time = 4;</code>
     */
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <code>optional int64 end_time = 4;</code>
     */
    public Builder setEndTime(long value) {
      
      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 end_time = 4;</code>
     */
    public Builder clearEndTime() {
      
      endTime_ = 0L;
      onChanged();
      return this;
    }

    private int batchSize_ ;
    /**
     * <code>optional int32 batch_size = 5;</code>
     */
    public int getBatchSize() {
      return batchSize_;
    }
    /**
     * <code>optional int32 batch_size = 5;</code>
     */
    public Builder setBatchSize(int value) {
      
      batchSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 batch_size = 5;</code>
     */
    public Builder clearBatchSize() {
      
      batchSize_ = 0;
      onChanged();
      return this;
    }

    private int batchDuration_ ;
    /**
     * <code>optional int32 batch_duration = 6;</code>
     */
    public int getBatchDuration() {
      return batchDuration_;
    }
    /**
     * <code>optional int32 batch_duration = 6;</code>
     */
    public Builder setBatchDuration(int value) {
      
      batchDuration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 batch_duration = 6;</code>
     */
    public Builder clearBatchDuration() {
      
      batchDuration_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object filePath_ = "";
    /**
     * <code>optional string file_path = 7;</code>
     */
    public java.lang.String getFilePath() {
      java.lang.Object ref = filePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string file_path = 7;</code>
     */
    public com.google.protobuf.ByteString
        getFilePathBytes() {
      java.lang.Object ref = filePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string file_path = 7;</code>
     */
    public Builder setFilePath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      filePath_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string file_path = 7;</code>
     */
    public Builder clearFilePath() {
      
      filePath_ = getDefaultInstance().getFilePath();
      onChanged();
      return this;
    }
    /**
     * <code>optional string file_path = 7;</code>
     */
    public Builder setFilePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      filePath_ = value;
      onChanged();
      return this;
    }

    private boolean isDummyData_ ;
    /**
     * <code>optional bool is_dummy_data = 8;</code>
     */
    public boolean getIsDummyData() {
      return isDummyData_;
    }
    /**
     * <code>optional bool is_dummy_data = 8;</code>
     */
    public Builder setIsDummyData(boolean value) {
      
      isDummyData_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_dummy_data = 8;</code>
     */
    public Builder clearIsDummyData() {
      
      isDummyData_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:org.dreamlab.gRPCHandler.BatchMetadata)
  }

  // @@protoc_insertion_point(class_scope:org.dreamlab.gRPCHandler.BatchMetadata)
  private static final org.dreamlab.gRPCHandler.BatchMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.dreamlab.gRPCHandler.BatchMetadata();
  }

  public static org.dreamlab.gRPCHandler.BatchMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatchMetadata>
      PARSER = new com.google.protobuf.AbstractParser<BatchMetadata>() {
    public BatchMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new BatchMetadata(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BatchMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatchMetadata> getParserForType() {
    return PARSER;
  }

  public org.dreamlab.gRPCHandler.BatchMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

