// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata.proto

package org.dreamlab.gRPCHandler;

public interface BatchMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.dreamlab.gRPCHandler.BatchMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string drone_id = 1;</code>
   */
  java.lang.String getDroneId();
  /**
   * <code>optional string drone_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getDroneIdBytes();

  /**
   * <code>optional string batch_id = 2;</code>
   */
  java.lang.String getBatchId();
  /**
   * <code>optional string batch_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getBatchIdBytes();

  /**
   * <code>optional int64 start_time = 3;</code>
   */
  long getStartTime();

  /**
   * <code>optional int64 end_time = 4;</code>
   */
  long getEndTime();

  /**
   * <code>optional int32 batch_size = 5;</code>
   */
  int getBatchSize();

  /**
   * <code>optional int32 batch_duration = 6;</code>
   */
  int getBatchDuration();

  /**
   * <code>optional string file_path = 7;</code>
   */
  java.lang.String getFilePath();
  /**
   * <code>optional string file_path = 7;</code>
   */
  com.google.protobuf.ByteString
      getFilePathBytes();

  /**
   * <code>optional bool is_dummy_data = 8;</code>
   */
  boolean getIsDummyData();
}
