// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata.proto

package org.dreamlab.gRPCHandler;

public interface FrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.dreamlab.gRPCHandler.Frame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes frame = 1;</code>
   * @return The frame.
   */
  com.google.protobuf.ByteString getFrame();
}
