// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata.proto

package org.dreamlab.gRPCHandler;

public interface JobDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.dreamlab.gRPCHandler.JobDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string batch_id = 1;</code>
   */
  java.lang.String getBatchId();
  /**
   * <code>optional string batch_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getBatchIdBytes();

  /**
   * <code>optional bytes frame = 2;</code>
   */
  com.google.protobuf.ByteString getFrame();

  /**
   * <code>optional bool is_cloud_exec = 3;</code>
   */
  boolean getIsCloudExec();

  /**
   * <code>optional string task_id = 4;</code>
   */
  java.lang.String getTaskId();
  /**
   * <code>optional string task_id = 4;</code>
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <code>optional string dnn_model = 5;</code>
   */
  java.lang.String getDnnModel();
  /**
   * <code>optional string dnn_model = 5;</code>
   */
  com.google.protobuf.ByteString
      getDnnModelBytes();

  /**
   * <code>optional string file_path = 6;</code>
   */
  java.lang.String getFilePath();
  /**
   * <code>optional string file_path = 6;</code>
   */
  com.google.protobuf.ByteString
      getFilePathBytes();
}
