// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata.proto

package org.dreamlab.gRPCHandler;

/**
 * Protobuf type {@code org.dreamlab.gRPCHandler.JobDetails}
 */
public  final class JobDetails extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.dreamlab.gRPCHandler.JobDetails)
    JobDetailsOrBuilder {
  // Use JobDetails.newBuilder() to construct.
  private JobDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JobDetails() {
    batchId_ = "";
    frame_ = com.google.protobuf.ByteString.EMPTY;
    isCloudExec_ = false;
    taskId_ = "";
    dnnModel_ = "";
    filePath_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private JobDetails(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            batchId_ = s;
            break;
          }
          case 18: {

            frame_ = input.readBytes();
            break;
          }
          case 24: {

            isCloudExec_ = input.readBool();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            taskId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            dnnModel_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            filePath_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.dreamlab.gRPCHandler.Metadata.internal_static_org_dreamlab_gRPCHandler_JobDetails_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.dreamlab.gRPCHandler.Metadata.internal_static_org_dreamlab_gRPCHandler_JobDetails_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.dreamlab.gRPCHandler.JobDetails.class, org.dreamlab.gRPCHandler.JobDetails.Builder.class);
  }

  public static final int BATCH_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object batchId_;
  /**
   * <code>optional string batch_id = 1;</code>
   */
  public java.lang.String getBatchId() {
    java.lang.Object ref = batchId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      batchId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string batch_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBatchIdBytes() {
    java.lang.Object ref = batchId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      batchId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FRAME_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString frame_;
  /**
   * <code>optional bytes frame = 2;</code>
   */
  public com.google.protobuf.ByteString getFrame() {
    return frame_;
  }

  public static final int IS_CLOUD_EXEC_FIELD_NUMBER = 3;
  private boolean isCloudExec_;
  /**
   * <code>optional bool is_cloud_exec = 3;</code>
   */
  public boolean getIsCloudExec() {
    return isCloudExec_;
  }

  public static final int TASK_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object taskId_;
  /**
   * <code>optional string task_id = 4;</code>
   */
  public java.lang.String getTaskId() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string task_id = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DNN_MODEL_FIELD_NUMBER = 5;
  private volatile java.lang.Object dnnModel_;
  /**
   * <code>optional string dnn_model = 5;</code>
   */
  public java.lang.String getDnnModel() {
    java.lang.Object ref = dnnModel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dnnModel_ = s;
      return s;
    }
  }
  /**
   * <code>optional string dnn_model = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDnnModelBytes() {
    java.lang.Object ref = dnnModel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dnnModel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILE_PATH_FIELD_NUMBER = 6;
  private volatile java.lang.Object filePath_;
  /**
   * <code>optional string file_path = 6;</code>
   */
  public java.lang.String getFilePath() {
    java.lang.Object ref = filePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filePath_ = s;
      return s;
    }
  }
  /**
   * <code>optional string file_path = 6;</code>
   */
  public com.google.protobuf.ByteString
      getFilePathBytes() {
    java.lang.Object ref = filePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBatchIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, batchId_);
    }
    if (!frame_.isEmpty()) {
      output.writeBytes(2, frame_);
    }
    if (isCloudExec_ != false) {
      output.writeBool(3, isCloudExec_);
    }
    if (!getTaskIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, taskId_);
    }
    if (!getDnnModelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dnnModel_);
    }
    if (!getFilePathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, filePath_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBatchIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, batchId_);
    }
    if (!frame_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, frame_);
    }
    if (isCloudExec_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, isCloudExec_);
    }
    if (!getTaskIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, taskId_);
    }
    if (!getDnnModelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dnnModel_);
    }
    if (!getFilePathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, filePath_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.dreamlab.gRPCHandler.JobDetails)) {
      return super.equals(obj);
    }
    org.dreamlab.gRPCHandler.JobDetails other = (org.dreamlab.gRPCHandler.JobDetails) obj;

    boolean result = true;
    result = result && getBatchId()
        .equals(other.getBatchId());
    result = result && getFrame()
        .equals(other.getFrame());
    result = result && (getIsCloudExec()
        == other.getIsCloudExec());
    result = result && getTaskId()
        .equals(other.getTaskId());
    result = result && getDnnModel()
        .equals(other.getDnnModel());
    result = result && getFilePath()
        .equals(other.getFilePath());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + BATCH_ID_FIELD_NUMBER;
    hash = (53 * hash) + getBatchId().hashCode();
    hash = (37 * hash) + FRAME_FIELD_NUMBER;
    hash = (53 * hash) + getFrame().hashCode();
    hash = (37 * hash) + IS_CLOUD_EXEC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsCloudExec());
    hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId().hashCode();
    hash = (37 * hash) + DNN_MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getDnnModel().hashCode();
    hash = (37 * hash) + FILE_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getFilePath().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.dreamlab.gRPCHandler.JobDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.dreamlab.gRPCHandler.JobDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.dreamlab.gRPCHandler.JobDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.dreamlab.gRPCHandler.JobDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.dreamlab.gRPCHandler.JobDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.dreamlab.gRPCHandler.JobDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.dreamlab.gRPCHandler.JobDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.dreamlab.gRPCHandler.JobDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.dreamlab.gRPCHandler.JobDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.dreamlab.gRPCHandler.JobDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.dreamlab.gRPCHandler.JobDetails prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.dreamlab.gRPCHandler.JobDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.dreamlab.gRPCHandler.JobDetails)
      org.dreamlab.gRPCHandler.JobDetailsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.dreamlab.gRPCHandler.Metadata.internal_static_org_dreamlab_gRPCHandler_JobDetails_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.dreamlab.gRPCHandler.Metadata.internal_static_org_dreamlab_gRPCHandler_JobDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.dreamlab.gRPCHandler.JobDetails.class, org.dreamlab.gRPCHandler.JobDetails.Builder.class);
    }

    // Construct using org.dreamlab.gRPCHandler.JobDetails.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      batchId_ = "";

      frame_ = com.google.protobuf.ByteString.EMPTY;

      isCloudExec_ = false;

      taskId_ = "";

      dnnModel_ = "";

      filePath_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.dreamlab.gRPCHandler.Metadata.internal_static_org_dreamlab_gRPCHandler_JobDetails_descriptor;
    }

    public org.dreamlab.gRPCHandler.JobDetails getDefaultInstanceForType() {
      return org.dreamlab.gRPCHandler.JobDetails.getDefaultInstance();
    }

    public org.dreamlab.gRPCHandler.JobDetails build() {
      org.dreamlab.gRPCHandler.JobDetails result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.dreamlab.gRPCHandler.JobDetails buildPartial() {
      org.dreamlab.gRPCHandler.JobDetails result = new org.dreamlab.gRPCHandler.JobDetails(this);
      result.batchId_ = batchId_;
      result.frame_ = frame_;
      result.isCloudExec_ = isCloudExec_;
      result.taskId_ = taskId_;
      result.dnnModel_ = dnnModel_;
      result.filePath_ = filePath_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.dreamlab.gRPCHandler.JobDetails) {
        return mergeFrom((org.dreamlab.gRPCHandler.JobDetails)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.dreamlab.gRPCHandler.JobDetails other) {
      if (other == org.dreamlab.gRPCHandler.JobDetails.getDefaultInstance()) return this;
      if (!other.getBatchId().isEmpty()) {
        batchId_ = other.batchId_;
        onChanged();
      }
      if (other.getFrame() != com.google.protobuf.ByteString.EMPTY) {
        setFrame(other.getFrame());
      }
      if (other.getIsCloudExec() != false) {
        setIsCloudExec(other.getIsCloudExec());
      }
      if (!other.getTaskId().isEmpty()) {
        taskId_ = other.taskId_;
        onChanged();
      }
      if (!other.getDnnModel().isEmpty()) {
        dnnModel_ = other.dnnModel_;
        onChanged();
      }
      if (!other.getFilePath().isEmpty()) {
        filePath_ = other.filePath_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.dreamlab.gRPCHandler.JobDetails parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.dreamlab.gRPCHandler.JobDetails) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object batchId_ = "";
    /**
     * <code>optional string batch_id = 1;</code>
     */
    public java.lang.String getBatchId() {
      java.lang.Object ref = batchId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        batchId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string batch_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBatchIdBytes() {
      java.lang.Object ref = batchId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        batchId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string batch_id = 1;</code>
     */
    public Builder setBatchId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      batchId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string batch_id = 1;</code>
     */
    public Builder clearBatchId() {
      
      batchId_ = getDefaultInstance().getBatchId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string batch_id = 1;</code>
     */
    public Builder setBatchIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      batchId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString frame_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes frame = 2;</code>
     */
    public com.google.protobuf.ByteString getFrame() {
      return frame_;
    }
    /**
     * <code>optional bytes frame = 2;</code>
     */
    public Builder setFrame(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      frame_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes frame = 2;</code>
     */
    public Builder clearFrame() {
      
      frame_ = getDefaultInstance().getFrame();
      onChanged();
      return this;
    }

    private boolean isCloudExec_ ;
    /**
     * <code>optional bool is_cloud_exec = 3;</code>
     */
    public boolean getIsCloudExec() {
      return isCloudExec_;
    }
    /**
     * <code>optional bool is_cloud_exec = 3;</code>
     */
    public Builder setIsCloudExec(boolean value) {
      
      isCloudExec_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_cloud_exec = 3;</code>
     */
    public Builder clearIsCloudExec() {
      
      isCloudExec_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object taskId_ = "";
    /**
     * <code>optional string task_id = 4;</code>
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string task_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string task_id = 4;</code>
     */
    public Builder setTaskId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      taskId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string task_id = 4;</code>
     */
    public Builder clearTaskId() {
      
      taskId_ = getDefaultInstance().getTaskId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string task_id = 4;</code>
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      taskId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dnnModel_ = "";
    /**
     * <code>optional string dnn_model = 5;</code>
     */
    public java.lang.String getDnnModel() {
      java.lang.Object ref = dnnModel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dnnModel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string dnn_model = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDnnModelBytes() {
      java.lang.Object ref = dnnModel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dnnModel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string dnn_model = 5;</code>
     */
    public Builder setDnnModel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dnnModel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string dnn_model = 5;</code>
     */
    public Builder clearDnnModel() {
      
      dnnModel_ = getDefaultInstance().getDnnModel();
      onChanged();
      return this;
    }
    /**
     * <code>optional string dnn_model = 5;</code>
     */
    public Builder setDnnModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dnnModel_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object filePath_ = "";
    /**
     * <code>optional string file_path = 6;</code>
     */
    public java.lang.String getFilePath() {
      java.lang.Object ref = filePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string file_path = 6;</code>
     */
    public com.google.protobuf.ByteString
        getFilePathBytes() {
      java.lang.Object ref = filePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string file_path = 6;</code>
     */
    public Builder setFilePath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      filePath_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string file_path = 6;</code>
     */
    public Builder clearFilePath() {
      
      filePath_ = getDefaultInstance().getFilePath();
      onChanged();
      return this;
    }
    /**
     * <code>optional string file_path = 6;</code>
     */
    public Builder setFilePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      filePath_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:org.dreamlab.gRPCHandler.JobDetails)
  }

  // @@protoc_insertion_point(class_scope:org.dreamlab.gRPCHandler.JobDetails)
  private static final org.dreamlab.gRPCHandler.JobDetails DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.dreamlab.gRPCHandler.JobDetails();
  }

  public static org.dreamlab.gRPCHandler.JobDetails getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JobDetails>
      PARSER = new com.google.protobuf.AbstractParser<JobDetails>() {
    public JobDetails parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new JobDetails(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JobDetails> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JobDetails> getParserForType() {
    return PARSER;
  }

  public org.dreamlab.gRPCHandler.JobDetails getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

