// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata

package org.dreamlab.gRPCHandler;

public final class Metadata {
  private Metadata() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_dreamlab_gRPCHandler_Ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_dreamlab_gRPCHandler_Ack_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_dreamlab_gRPCHandler_BatchMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_dreamlab_gRPCHandler_BatchMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_dreamlab_gRPCHandler_JobDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_dreamlab_gRPCHandler_JobDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_dreamlab_gRPCHandler_OutputDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_dreamlab_gRPCHandler_OutputDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_dreamlab_gRPCHandler_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_dreamlab_gRPCHandler_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010metadata\022\030org.dreamlab.gRPCHandler\"9\n\003" +
      "Ack\022\017\n\007message\030\001 \001(\t\022\017\n\007task_id\030\002 \001(\t\022\020\n" +
      "\010batch_id\030\003 \001(\t\"\257\001\n\rBatchMetadata\022\020\n\010dro" +
      "ne_id\030\001 \001(\t\022\020\n\010batch_id\030\002 \001(\t\022\022\n\nstart_t" +
      "ime\030\003 \001(\003\022\020\n\010end_time\030\004 \001(\003\022\022\n\nbatch_siz" +
      "e\030\005 \001(\005\022\026\n\016batch_duration\030\006 \001(\005\022\021\n\tfile_" +
      "path\030\007 \001(\t\022\025\n\ris_dummy_data\030\010 \001(\010\"{\n\nJob" +
      "Details\022\020\n\010batch_id\030\001 \001(\t\022\r\n\005frame\030\002 \001(\014" +
      "\022\025\n\ris_cloud_exec\030\003 \001(\010\022\017\n\007task_id\030\004 \001(\t" +
      "\022\021\n\tdnn_model\030\005 \001(\t\022\021\n\tfile_path\030\006 \001(\t\"3" +
      "\n\rOutputDetails\022\017\n\007task_id\030\001 \001(\t\022\021\n\tdnn_" +
      "model\030\002 \001(\t\"\007\n\005Empty2`\n\010JavaConn\022T\n\010NewB" +
      "atch\022\'.org.dreamlab.gRPCHandler.BatchMet" +
      "adata\032\035.org.dreamlab.gRPCHandler.Ack\"\0002]" +
      "\n\nInferencer\022O\n\006Submit\022$.org.dreamlab.gR" +
      "PCHandler.JobDetails\032\035.org.dreamlab.gRPC" +
      "Handler.Ack\"\0002f\n\016PostInferencer\022T\n\006Submi" +
      "t\022\'.org.dreamlab.gRPCHandler.OutputDetai" +
      "ls\032\037.org.dreamlab.gRPCHandler.Empty\"\000B\002P" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_dreamlab_gRPCHandler_Ack_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_dreamlab_gRPCHandler_Ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_dreamlab_gRPCHandler_Ack_descriptor,
        new java.lang.String[] { "Message", "TaskId", "BatchId", });
    internal_static_org_dreamlab_gRPCHandler_BatchMetadata_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_dreamlab_gRPCHandler_BatchMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_dreamlab_gRPCHandler_BatchMetadata_descriptor,
        new java.lang.String[] { "DroneId", "BatchId", "StartTime", "EndTime", "BatchSize", "BatchDuration", "FilePath", "IsDummyData", });
    internal_static_org_dreamlab_gRPCHandler_JobDetails_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_dreamlab_gRPCHandler_JobDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_dreamlab_gRPCHandler_JobDetails_descriptor,
        new java.lang.String[] { "BatchId", "Frame", "IsCloudExec", "TaskId", "DnnModel", "FilePath", });
    internal_static_org_dreamlab_gRPCHandler_OutputDetails_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_dreamlab_gRPCHandler_OutputDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_dreamlab_gRPCHandler_OutputDetails_descriptor,
        new java.lang.String[] { "TaskId", "DnnModel", });
    internal_static_org_dreamlab_gRPCHandler_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_dreamlab_gRPCHandler_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_dreamlab_gRPCHandler_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
