// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata

package org.dreamlab.gRPCHandler;

public interface OutputDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.dreamlab.gRPCHandler.OutputDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string task_id = 1;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <code>string task_id = 1;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <code>string dnn_model = 2;</code>
   * @return The dnnModel.
   */
  java.lang.String getDnnModel();
  /**
   * <code>string dnn_model = 2;</code>
   * @return The bytes for dnnModel.
   */
  com.google.protobuf.ByteString
      getDnnModelBytes();

  /**
   * <code>string result = 3;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 3;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
